// Generated by hazo_auth - do not edit manually
// Page: /hazo_auth/verify_email
import { VerifyEmailPage } from "hazo_auth/pages/verify_email";

export default function Page() {
  return <VerifyEmailPage />;
}
