// Generated by hazo_auth - do not edit manually
// Route: /api/hazo_auth/user_management/permissions
// Methods: GET, POST, PUT, DELETE
export { 
  userManagementPermissionsGET as GET,
  userManagementPermissionsPOST as POST,
  userManagementPermissionsPUT as PUT,
  userManagementPermissionsDELETE as DELETE
} from "hazo_auth/server/routes";







