// Generated by hazo_auth - do not edit manually
// Route: /api/hazo_auth/user_management/users
// Methods: GET, POST, PATCH
export { 
  userManagementUsersGET as GET,
  userManagementUsersPOST as POST,
  userManagementUsersPATCH as PATCH 
} from "hazo_auth/server/routes";




