// Generated by hazo_auth - do not edit manually
// Route: /api/hazo_auth/user_management/roles
// Methods: GET, POST, PUT
export { 
  userManagementRolesGET as GET,
  userManagementRolesPOST as POST,
  userManagementRolesPUT as PUT
} from "hazo_auth/server/routes";




