// Generated by hazo_auth - do not edit manually
// Page: /hazo_auth/reset_password
import { ResetPasswordPage } from "hazo_auth/pages/reset_password";

export default function Page() {
  return <ResetPasswordPage />;
}
