// Generated by hazo_auth - do not edit manually
// Page: /hazo_auth/my_settings
import { MySettingsPage } from "hazo_auth/pages/my_settings";

export default function Page() {
  return <MySettingsPage />;
}
