// Generated by hazo_auth - do not edit manually
// Route: /api/hazo_auth/user_management/users/roles
// Methods: GET, POST, PUT
export { 
  userManagementUsersRolesGET as GET,
  userManagementUsersRolesPOST as POST,
  userManagementUsersRolesPUT as PUT
} from "hazo_auth/server/routes";

