// Generated by hazo_auth - do not edit manually
// Page: /hazo_auth/forgot_password
import { ForgotPasswordPage } from "hazo_auth/pages/forgot_password";

export default function Page() {
  return <ForgotPasswordPage />;
}
